interface OpenshiftEnv {
	OPENSHIFT_NODEJS_IP: string;
	OPENSHIFT_NODEJS_PORT: number;
	OPENSHIFT_APP_DNS: string;
	OPENSHIFT_APP_NAME: string;
	OPENSHIFT_APP_UUID: string;
	OPENSHIFT_SECRET_TOKEN: string;
	OPENSHIFT_HOMEDIR : string;
	OPENSHIFT_DATA_DIR : string;
	OPENSHIFT_REPO_DIR: string;
	OPENSHIFT_TMP_DIR: string;
	OPENSHIFT_LOG_DIR : string;
	LOGSHIFTER_NODEJS_MAX_FILESIZE : string;
	LOGSHIFTER_NODEJS_MAX_FILES : number;
	OPENSHIFT_MAX_SESSIONS_PER_GEAR : number;
	OPENSHIFT_NODEJS_LD_LIBRARY_PATH_ELEMENT : string;
	OPENSHIFT_GEAR_DNS : string;
	OPENSHIFT_GEAR_NAME : string;
	OPENSHIFT_GEAR_UUID : string;
	NODE_ENV :string
}