#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"


#  On slave/serving gears, need to do the install as part of deploy
#  so check if its needed. Just ensure the custom Node[.js] version is
#  installed.
ensure_node_is_installed

#launch gulp to set up project
OLD_HOME=$HOME
export HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR
./node_modules/.bin/gulp
export HOME=$OLD_HOME
export NODE_ENV=production